# This is a basic workflow to help you get started with Actions

name: Generate PDF labels from LaTeX files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: make pdf
        run: for x in *.tex ; do pdflatex -output-directory=output $x ; done
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-output
          path: "output/*.pdf"

      - name: Commit pdf
        run: |
          git config --global --add safe.directory /__w/solatex_labels/solatex_labels
          git config --global --add safe.directory $PWD
          git config --global user.name 'Automated Workflow'
          git config --global user.email 'rc9000@users.noreply.github.com'
          git add output/*.pdf
          git commit -am "worflow PDF generation"
          git push

